VIDA-NYU/reprozip

reprounzip/reprounzip/unpackers/common/misc.py, tests/test_unpackers_common.py
This makes it faster to run multiple experiment steps, for things like docker which need to spin up containers and commit images between each one.
Finishes #100
For instance:
```
reprounzip docker run my-experiment.docker 1-6
```
=> Allow selection of multiple runs at once

CHANGELOG.md, reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/pack_info.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/unpackers/default.py, tests/test_unpackers_common.py
=> Convenience commands

docs/developerguide.rst, docs/index.rst, docs/unpacked-format.rst, docs/unpacking.rst
=> Internal doc: unpacked directory formats

reprounzip/reprounzip/common.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/unpackers/default.py, reprozip/reprozip/common.py, tests/functional.py
Allow any file to be downloaded (uploaded?) via its full path, in addition to input&output files referenced by their short name.
=> Download file from full path

reprounzip/reprounzip/pack_info.py
This adds `reprounzip info --json`.
=> JSON output for reprounzip info

reprounzip-qt/reprounzip_qt/gui.py, reprounzip-qt/reprounzip_qt/reprounzip_interface.py, reprounzip/reprounzip/common.py, reprozip/reprozip/common.py
This adds the unpacker options to the unpacking tab.
Needs to be tested thoroughly. Doesn't provide raw Docker options, which are needed to run things like webservers (stacked-up).
=> GUI unpacker options

news.html
This makes the news a little more interesting. Is it too much?
=> Add short descriptions for ReproZip releases

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-qt/reprounzip_qt/gui/common.py, reprounzip-qt/reprounzip_qt/gui/run.py, reprounzip-qt/reprounzip_qt/gui/unpack.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py
Add explicit options to enable port forwarding. Fixes #212.
=> Port forwarding options

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Fix links and such.
Alternatively we might want to use one of the CoC [newly suggested by GitHub](https://twitter.com/CoralineAda/status/863156332488216576). Or host the linked one here.
=> Contributing tweak

.gitignore, reprounzip-qt/reprounzip_qt/gui/__init__.py, reprounzip-qt/reprounzip_qt/gui/run.py, reprounzip-qt/reprounzip_qt/gui/unpack.py, reprounzip-qt/reprounzip_qt/main.py, reprounzip-qt/setup.py, scripts/macos/ReproUnzip.pkgproj, scripts/macos/app-shim/ReproUnzip.app/Contents/Info.plist, scripts/macos/app-shim/ReproUnzip.app/Contents/MacOS/reprounzip-qt, scripts/macos/app-shim/reprounzip-qt.c, scripts/macos/reprounzip-qt
=> New installer with single Python installation and .app shim

reprounzip-qt/reprounzip_qt/gui/__init__.py, scripts/register-linux.sh
See #216
Mac is done automatically, this handles Linux (when application is first started).
=> Automatically register with .RPZ files on Linux

reprounzip/reprounzip/common.py, reprozip/reprozip/common.py, reprozip/reprozip/tracer/linux_pkgs.py
Useful for categorizing/filtering/visualizing
=> Add "section" information to Debian packages

reprounzip/reprounzip/unpackers/graph.py, tests/test_graph.py
From here: [qwang70/yw-idcc-17_1 examples/LIGO/supplementary/README.md](https://github.com/qwang70/yw-idcc-17_1/blob/9302e9dddd9361de0c66a5aabefdef4db761d84c/examples/LIGO/supplementary/README.md)
=> Update graph DOT to get a better visualization

docs/conf.py, docs/man/reprounzip-docker.1, docs/man/reprounzip-vagrant.1, docs/man/reprounzip.1, docs/man/reprozip.1, docs/traceschema.rst, reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py
Add man pages.
Resources:
* http://www.tldp.org/HOWTO/Man-Page/q3.html
* https://linux.die.net/man/7/man
* https://www.gnu.org/software/groff/manual/html_node/Manipulating-Filling-and-Adjusting.html
=> Add man pages

scripts/linux-wheels.sh
=> Build binary wheels of 'reprozip' with manylinux2

reprounzip-qt/reprounzip_qt/gui/__init__.py, reprounzip-qt/reprounzip_qt/reprounzip_interface.py, reprounzip/reprounzip/pack_info.py, reprounzip/reprounzip/unpackers/common/packages.py, reprounzip/reprounzip/unpackers/default.py, reprounzip/setup.py, reprozip/reprozip/tracer/linux_pkgs.py, reprozip/reprozip/tracer/trace.py, reprozip/setup.py
=> Use distro instead of platform.linux_distribution()

reprounzip-docker/reprounzip/unpackers/docker.py
=> Fix Docker upload erroring with missing /bin/sh

reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py
Attempts to fix #235
I don't know if that makes a difference for Elasticsearch.
=> Vagrant: make /experimentroot a mountpoint (bind mount)

reprounzip-docker/reprounzip/unpackers/docker.py
This removes the need to copy the tarball inside the image to uncompress it, which lead to the files being in the image twice (once in tarball and once in final location).
This does need Docker to be recent enough to support BuildKit (2018?)
=> Use Docker BuildKit's RUN --mount to build images

reprounzip-docker/reprounzip_docker.py, tests/functional.py
Even though buildkit is generally available, there are situations where `RUN --mount` doesn't work (for example when using userns-remap, possible rootless Docker).
See #375
=> Make buildkit optional

reprounzip/reprounzip/common.py, reprounzip/reprounzip/pack_info.py, reprozip/reprozip/common.py, tests/test_reprounzip.py, tests/test_unpackers_common.py
=> Implement EXTENSIONS directory in RPZ bundle format

reprozip/native/ptrace_utils.c, reprozip/native/ptrace_utils.h, reprozip/native/syscalls.c, reprozip/native/tracer.h
=> Add more syscalls
