VIDA-NYU/reprozip

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py
For Vagrant, set the hostname to the original experiment's machine's.
This is needed for X11 support (#96), so that we know what the hostname is. With other unpackers (except Docker), we also know what the hostname is since it's the local machine's.
=> Restores hostname

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/run_command.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/packages.py, reprounzip/reprounzip/unpackers/common/x11.py, reprounzip/reprounzip/unpackers/default.py, reprounzip/setup.py
This allows the experiment to connect to the host's X server
It detects how to connect to the local X server (via `$DISPLAY`), extract the authentication cookie (from `.Xauthority`), injects that in the experiment, and establishes a tunnel from the experiment (in the VM for vagrant, on a different local TCP port for chroot) to the local X server (TCP or UNIX socket).
Implements #39
Uses #95 (setting the hostname in the Vagrant VM)
=> X11 support

reprozip/native/syscalls.c, reprozip/native/syscalls.h, reprozip/native/tracer.c, reprozip/native/tracer.h, tests/functional.py, tests/threads.c, tests/threads2.c
Previously, I was relying on the syscall-return-stop out of execve() to detect that an exec had happened. This had a number of drawbacks:
* Can't be sure which thread executed (although race conditions here are not common)
* Need to read orig_eax on syscall-return-stop to know which syscall we are returning from, although in normal circumstances we should know (it's the one we entered). Also, that value might apparently be set wrong...
* Needed to work around i386/x86_64 transitions, as Linux could report a thread going out of "syscall 59", number for execve in x86_64, although the new program is running in i386 mode
We now react to PTRACE_EVENT_EXEC and do the work there. We then set the flag PROCFLAG_EXECD, so that we know the next syscall-in/out-stop is in fact a return from execve, no …
=> Use PTRACE_EVENT_EXEC instead of syscall return

.travis/install.sh, reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py
=> Running experiment from very different systems

reprozip/native/syscalls.c, reprozip/native/syscalls.h, reprozip/native/tracer.c, reprozip/native/tracer.h, tests/functional.py, tests/vfork.c
Similar to #114 but for forking instead of exec.
Fixes #121: vfork() is the only one that doesn't work right now (but happens in real-life in my compiler).
Previously, I was only using the syscall-return-stop out of fork(), vfork() or clone() to detect that a successful process creation had happened. This was a problem because syscall return can happen either before or after the process is created. Thus I waited for both to happen before resuming the new process; problem is that vfork() won't let the parent return until the child has exited or called exec; thus we deadlock on vfork().
=> Use PTRACE_EVENT_FORK, ... instead of syscall out

reprounzip/reprounzip/unpackers/common/misc.py
If no run is selected, error out (unless there is only one).
This means that there is now no way to run several runs at once, although the code everywhere still supports it.
=> No longer run all runs by default

reprozip/reprozip/tracer/linux_pkgs.py
This reads all the *.list files directly, and only once. It should be way faster than using dpkg -S, especially with large experiments (e.g. large number of system files).
Fixes #113
=> Fast dpkg lookup by using *.list files directly

reprounzip/reprounzip/common.py, reprozip/native/database.h, reprozip/native/syscalls.c, reprozip/reprozip/common.py, reprozip/reprozip/tracer/trace.py, tests/functional.py, tests/rename.c
Handles rename(), symlink(), link(), and the *at variants (with AT_FDCWD only; cf c233d3e1).
Also adds the FILE_LINK flag, which also means lstat() doesn't mark the link target as read anymore.
Fixes #126
=> Rename & symlink syscalls

reprounzip-docker/reprounzip/unpackers/docker.py
Right now, the container created from the previous 'reprounzip docker run' command is discarded when calling this again, and we run from the image instead. This means that changes caused by one run are not seen by the next. This looked ok at first but means that the data-flow expected for reprounzip-vistrails doesn't work at all.
This patch changes 'reprounzip docker run' to update current_image so that changes are kept.
=> Docker: keep changes to environment

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/common.py, reprounzip/reprounzip/pack_info.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/unpackers/default.py, reprounzip/reprounzip/unpackers/graph.py, reprounzip/reprounzip/utils.py, reprozip/reprozip/common.py, reprozip/reprozip/pack.py, reprozip/reprozip/utils.py, tests/functional.py
We need to decompress the whole tar.gz to read the configuration file (this is a tar.gz limitation). This can take a long time, even if we just need the small configuration file.
=> 'reprounzip info' can take a long time

reprozip/native/syscalls.c, reprozip/native/tracer.c
This makes the log messages about unhandled system calls being used, or the experiment connecting to servers or accepting connections, not display by default (need --verbose).
Fixes #128
The bad thing is that these messages might be interesting and give clues about reproducibility concerns. Of course they are still in `~/.reprozip/log`.
Interesting note: with this, there are no messages with level WARNING in the C tracer...
=> Turn some warning into info messages

docs/graph.rst, docs/index.rst, docs/unpacking.rst, reprounzip/reprounzip/unpackers/graph.py, tests/common.py, tests/test_graph.py, tests/test_reprozip.py
This allows to generate graphs that are not too huge to be rendered.
* Processes can be either:
* Every process and thread
* Only processes (aggregate threads)
* Only runs (aggregate all the processes of each run)
* Packages can be either:
* Every file of every package
* Aggregate by package
* Ignore packages (treat every file as an "other file")
* Other files can be either:
* Every file
* Only input & output files
* Not shown
~~The DOT-writing code looks really weird, and should probably be refactored.~~
=> Add selectable levels of detail to the 'graph' command

CHANGELOG.md, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, tests/functional.py
This adds --memory for reprounzip-vagrant, to set the amount of RAM needed.
This can still be changed from VirtualBox once the machine has been built. It still defaults to using whatever the box is configured for.
=> More RAM for Vagrant

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/unpackers/default.py
It might be useful to let the experiment have some environment variables from the host, instead of dropping them or replacing the value with the packing machine's.
Example: `$OMPI_*`
=> Pass-through environment variables from the host

CHANGELOG.md, reprounzip/reprounzip/utils.py, reprounzip/setup.py, reprozip/reprozip/utils.py, reprozip/setup.py, scripts/conda/reprounzip/meta.yaml, scripts/conda/reprozip/meta.yaml
This uses [requests](http://python-requests.org/) to download file, which is easier and more secure.
requests is already used in usagestats, so it makes sense to use it for everything.
=> Use requests to implement download_file

CHANGELOG.md, reprounzip/reprounzip/common.py, reprounzip/reprounzip/parameters.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/utils.py, reprounzip/setup.py, reprozip/reprozip/common.py, reprozip/reprozip/utils.py, reprozip/setup.py, scripts/conda/reprounzip/meta.yaml, scripts/conda/reprozip/meta.yaml
Depends on requests, #173
This downloads a small `parameters.json` file that will contain things like busybox and rpzsudo URLs, Vagrant boxes and Docker images mappings, etc so that these can be updated without doing a release (and without people having to upgrade).
I'm probably hosting this on `reprozip-stats.poly.edu` since it's there and I have the certificate trickery working.
=> Download parameters

reprounzip-docker/reprounzip/unpackers/docker.py
Fix #181
This is useful when running on a different machine, for instance starting a server on the cloud.
No local state is altered, the container is not cleaned up, and `-d -t` is passed instead of `-i -t` so the container keep running in the background.
=> Add --detach option to docker run

reprounzip/reprounzip/common.py, reprozip/reprozip/common.py, reprozip/reprozip/main.py, reprozip/reprozip/pack.py, reprozip/reprozip/tracer/trace.py, reprozip/reprozip/traceutils.py, scripts/test_bug_13676.py, scripts/test_bug_23058.py, tests/test_reprozip.py
Fix #159
Adds a new `reprozip combine` command that reads in multiple trace databases and merges them into one (with all the combined runs).
=> Merge traces

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/common.py, reprozip/reprozip/common.py
The loop building the list of files that is written to `rpz-files.list`, for both Vagrant and Docker, was very slow because the lookups in the data TAR (to check that the files are there) perform a list scan.
We now build a set of all the files in that TAR first and lookup files in that, which is faster in practical situations.
=> Make building the list for TAR faster

docs/packing.rst, reprozip/reprozip/main.py, reprozip/reprozip/tracer/trace.py, tests/functional.py
Previously, not specifying `--continue` would discard the existing trace, which was dangerous.
Now, a new option `--overwrite` has been added to explicitly request this behavior, and if none of `--continue` or `--overwrite` are specified and a trace exists, reprozip will ask what to do (batch scripts should thus include one of the two in order to run uninterrupted).
+-------------+------------+--------------+------------------------+
| --overwrite | --continue | trace exists | action                 |
+-------------+------------+--------------+------------------------+
|     Yes     |     Yes    |       *      | error                  |
|      *      |     No     |      No      | create new trace       |
|     No      |     Yes    |      No      | create new trace, warn |
|     No      | …
=> --continue overhaul

reprozip/reprozip/filters.py, reprozip/reprozip/tracer/trace.py, reprozip/setup.py
Fix #201
Adds plugins through entry_points to reprozip to go over the list of detected files before writing out the configuration.
This is useful to filter out .pyc files, remove code from input files, ...
=> File filters for specific situations through plugins

README.md
Suggested for openjournals/joss-reviews#107
You may want to extend the (c) Copyright to include all the [contributors](https://github.com/ViDA-NYU/reprozip/graphs/contributors) (and their institutions)
=> README: Add Contribution section and License info

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/unpackers/default.py
If an experiment brings its own resolv.conf which lists an unreachable DNS server, the experiment won't be able to connect to the Internet.
=> Don't let experiment override resolv.conf

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-qt/reprounzip_qt/gui/unpack.py, reprounzip-qt/reprounzip_qt/qt_terminal.py, reprounzip-qt/reprounzip_qt/reprounzip_interface.py
This adds a drop-down in the options for the Docker unpacker allowing the user to choose one of the defined machines, if he has docker-machine installed.
The core Docker unpacker saves the docker-machine configuration in the unpacked metadata after setup/build, this is only used by the GUI for the run step (core unpacker won't use that).
=> Docker machine support for the GUI

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py, reprounzip/reprounzip/unpackers/common/x11.py, tests/test_reprounzip.py
Right now, `reprounzip run` does the work, looking up environment variables/command-lines/... This makes the created Docker images useless by themselves, you need to run them through reprounzip.
By moving some of the run logic from Python to an entrypoint (shell), I can make an image that can be run directly from Docker as well.
Step towards #169
```
$ docker run -ti --rm reprounzip_image_351oi6lubs help
Image built from reprounzip-docker
Usage: docker run <image> [cmd word [word ...]] [run <R>]
`cmd ...` changes the command for the next `run` option
`run <name|number>` runs the specified run
By default, all the runs are executed.
The runs in this image are:
get_data: python 01_getdata.py
build_classifier: python 02_classifier.py
predict: python 03_predict.py
evaluate: python …
```
=> Create stand-alone Docker images via entrypoint

docs/install.rst
Those are apparently necessary (for pycrypto).
=> Reported at PresQt: libssl-dev necessary to build reprounzip-vagrant?

reprozip/native/database.c, reprozip/native/tracer.c, reprozip/reprozip/main.py, reprozip/reprozip/tracer/trace.py, tests/functional.py
Replaces #281
Returns the exit status from the original command, not always 0. The `trace` and `testrun` commands now use 125 for an internal error.
=> Return the traced command's status, not 0

reprozip/native/syscalls.c, reprozip/native/tracer.c, tests/functional.py
=> Warn if executing a set-uid or set-gid binary

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip/reprounzip/unpackers/common/misc.py
Fixes #291
This uses `pty.spawn()` to allocate a pty if we need to before calling `docker run -ti`
There are some weird issues with the exitcode, which this might make worse. Should probably look into using the inspect JSON only and disregard the `docker run` exitcode.
=> Make `reprounzip docker run` work with a terminal by using pty.spawn()

reprounzip-qt/reprounzip_qt/gui/__init__.py, reprounzip-qt/reprounzip_qt/gui/common.py, reprounzip-qt/reprounzip_qt/gui/run.py, reprounzip-qt/reprounzip_qt/gui/unpack.py, reprounzip-qt/reprounzip_qt/main.py, reprounzip-qt/reprounzip_qt/qt_terminal.py, reprounzip-qt/reprounzip_qt/reprounzip_interface.py, reprounzip-qt/reprounzip_qt/usage.py, reprounzip-qt/setup.py
It might be useful to have reports from there too.
Currently this means they'll have to depend on reprounzip, for 1.1 I plan on breaking up the "common" modules to different PyPI packages.
=> Add usage reporting to reprounzip-qt and reprozip-jupyter

reprounzip-docker/reprounzip/unpackers/docker.py
@remram44 - I noticed this when trying to run:
```
$ reprounzip docker run --expose-port 3000:3000 target
...
docker: Invalid containerPort: 3000tcp.
```
=> add missing '/' when converting 'expose-port' to docker's '-p' flag

reprozip/reprozip/tracer/linux_pkgs.py
I used to call `dpkg-query -S` on each file to identify which package it came from, but because this was too slow I replaced it with reading the `/var/lib/dpkg/info/*.list` files directly (PR #124).
However it turns out that `dpkg-query -S` can be called on multiple files at once, even though the man page does not hint at this at all.
Fixes #329
=> Use dpkg-query to identify Debian packages

reprounzip/reprounzip/common.py, reprozip/reprozip/common.py, tests/__main__.py
=> Don't log to ~/.reprozip/log when running tests

reprounzip/reprounzip/unpackers/common/x11.py
Looks like some entries can have an empty (size 0) "number" field. Those should not cause parsing to fail, especially since other entries might be suitable.
Reported by @euanc
=> Handle Xauthority files with empty number field

reprounzip-docker/reprounzip/unpackers/docker.py
I changed the decoding done in the docker unpacker to UTF-8 from ascii.
The unpacker wasn't working for me until i did this (localization
issue?) Is there any reason not to use UTF-8 decoding ihere?
=> Changed decoding to UTF-8

reprounzip-docker/reprounzip/unpackers/docker.py, reprounzip-vagrant/reprounzip/unpackers/vagrant/__init__.py, reprounzip/reprounzip/parameters.py, reprounzip/reprounzip/unpackers/common/__init__.py, reprounzip/reprounzip/unpackers/common/misc.py
This will behave correctly in situations where we need to unpack a file or link over a directory, without wiping whole directories when unneeded.
Written in Rust using the [`tar`](https://docs.rs/tar/) library and compiled to a static executable (repo: [remram44/rpztar](https://github.com/remram44/rpztar)). Similar to `rpzsudo` but I couldn't easily implement tar support in C...
Should probably be used for Vagrant as well (at least when `use_chroot=False`).
This also allows us to support Docker images or Vagrant images that don't have tar.
=> Develop custom 'tar' replacement to merge bundle with existing system

reprounzip/reprounzip/unpackers/default.py
It doesn't look like `ld-linux.so` uses PATH to locate the target, so we'll have to give the full path. This means it won't get its expected `arg0` but I don't see how to work around it.
=> Fix invocation through PATH in directory unpacker

reprounzip/reprounzip/common.py, reprozip/native/database.h, reprozip/native/syscalls.c, reprozip/reprozip/common.py, reprozip/reprozip/tracer/trace.py
Fixes #45
This is a rather big change because it add a new flag for files in the `opened_files` table, `FILE_SOCKET`. The Python tracer then checks that against systemd UNIX socket locations to print a warning.
=> Print warnings for systemd
